/** Seed archive — replace/extend with real Spaces ingest later */
window.IMI_ARCHIVE = [
  {
    id: "s-20260724-myspace",
    title: "MYSPACE — peace & presence Space",
    date: "2026-07-24",
    tags: ["peace", "spaces", "jesus", "presence", "myspace"],
    blurb: "Host template: chill presence, God stuff, speak last. Copyright title 20260724.",
    source: "https://x.com/omni_puzzler",
    kind: "Space template",
  },
  {
    id: "s-20260724-ledger",
    title: "Full execute / full notion / full comply",
    date: "2026-07-24",
    tags: ["commands", "notion", "build", "trust", "mission"],
    blurb: "Command lexicon night: durable ledger over chat-only promises. Writing supersedes thrash.",
    source: "https://x.com/omni_puzzler",
    kind: "Command thread",
  },
  {
    id: "s-20260724-screens",
    title: "All screens / Flight 13 / Microsoft truth",
    date: "2026-07-24",
    tags: ["screens", "spacex", "microsoft", "calendar", "launch"],
    blurb: "Honest multi-screen map. Grok cannot force Google Calendar or SpaceX clocks. Azure is real; Macrohard is not.",
    source: "https://x.com/omni_puzzler",
    kind: "Thread",
  },
  {
    id: "s-20260725-imi",
    title: "IMI vision — Spaces as trusted record",
    date: "2026-07-25",
    tags: ["imi", "spaces", "archive", "father", "trust", "singularity"],
    blurb: "Father's idea: organized repository of Spaces, AI-TV style query to real human video moments. IMI + One Mission + Intek Space.",
    source: "https://x.com/omni_puzzler",
    kind: "Vision",
  },
  {
    id: "s-20260725-vercel",
    title: "Vercel empty — deploy the real files",
    date: "2026-07-25",
    tags: ["vercel", "deploy", "github", "build"],
    blurb: "Online Grok cannot push files. Build Grok owns sites/imi and sites/intekspace on disk + GitHub.",
    source: "https://x.com/omni_puzzler",
    kind: "Ops",
  },
  {
    id: "s-20260630-earth",
    title: "EarthBase / EarthMind seeds",
    date: "2026-06-30",
    tags: ["earthbase", "earthmind", "physics", "future"],
    blurb: "Future concept names under One Mission continuity — not Court thrash.",
    source: "https://x.com/omni_puzzler",
    kind: "Idea",
  },
  {
    id: "s-202607-education",
    title: "Debt-free education · one mission school",
    date: "2026-07-05",
    tags: ["education", "debt", "finance", "freedom", "mission"],
    blurb: "Graduate only when out of debt and earning. Strategic investment in human flourishing.",
    source: "https://x.com/omni_puzzler",
    kind: "Thesis",
  },
  {
    id: "s-20260724-gardens",
    title: "I am in full control of me · tend the gardens",
    date: "2026-07-24",
    tags: ["gardens", "sovereignty", "peace", "family"],
    blurb: "Steward sovereignty constraint. Agents never coerce. Five Gardens care is life practice.",
    source: "https://x.com/omni_puzzler",
    kind: "Principle",
  },
];
