/**
 * IMI archive — real Spaces first (father's idea: trusted human moments).
 * Live Space URL is the point — not only seed blurbs.
 */
window.IMI_ARCHIVE = [
  {
    id: "s-20260727-space-titles",
    title: "Request Space time — pick a topic, DM a number",
    date: "2026-07-27",
    tags: ["spaces", "titles", "request", "myspace", "host", "menu"],
    blurb:
      "Want real Space time — not a vague someday? Open the topic catalog, pick a number, and DM @omni_puzzler that number. Guests speak first; host speaks last. Chill presence. God stuff welcome. This is how you get a room.",
    source: "https://x.com/omni_puzzler/status/2081550590174233015?s=20",
    kind: "X Article",
    pin: true,
  },

  {
    id: "s-20260725-myspace-live",
    title: "MYSPACE — live Space (thePuzzler)",
    date: "2026-07-25",
    tags: ["myspace", "live", "peace", "spaces", "jesus", "presence", "featured"],
    blurb:
      "Real X Space — chill presence, God stuff, guests first, host speaks last. This is the IMI idea in the wild: a meeting of the mind you can open as it happened, not a rewritten summary.",
    source: "https://x.com/i/spaces/1nGeLLdlnrRKX?s=20",
    kind: "Live Space",
    featured: true,
  },
  {
    id: "s-20260724-myspace",
    title: "MYSPACE — host posture (copyright 20260724)",
    date: "2026-07-24",
    tags: ["peace", "spaces", "jesus", "presence", "myspace", "template"],
    blurb: "Same spirit as the live Space: chill, speak last. Opener frozen 20260724. Open the live Space card above for the real room.",
    source: "https://x.com/i/spaces/1nGeLLdlnrRKX?s=20",
    kind: "Space note",
  },
  {
    id: "s-20260724-ledger",
    title: "Full execute / full notion / full comply",
    date: "2026-07-24",
    tags: ["commands", "notion", "build", "trust", "mission"],
    blurb: "Command lexicon night: durable ledger over chat-only promises. Writing supersedes thrash.",
    source: "https://x.com/omni_puzzler",
    kind: "Command thread",
  },
  {
    id: "s-20260724-screens",
    title: "All screens / Flight 13 / Microsoft truth",
    date: "2026-07-24",
    tags: ["screens", "spacex", "microsoft", "calendar", "launch"],
    blurb: "Honest multi-screen map. Grok cannot force Google Calendar or SpaceX clocks. Azure is real; Macrohard is not.",
    source: "https://x.com/omni_puzzler",
    kind: "Thread",
  },
  {
    id: "s-20260725-imi",
    title: "IMI vision — Spaces as trusted record",
    date: "2026-07-25",
    tags: ["imi", "spaces", "archive", "father", "trust", "singularity"],
    blurb: "Father's idea: organized repository of Spaces, AI-TV style query to real human video moments. IMI + One Mission + Intek Space.",
    source: "https://x.com/omni_puzzler",
    kind: "Vision",
  },
  {
    id: "s-20260725-vercel",
    title: "Vercel empty — deploy the real files",
    date: "2026-07-25",
    tags: ["vercel", "deploy", "github", "build"],
    blurb: "Online Grok cannot push files. Build Grok owns sites/imi and sites/intekspace on disk + GitHub.",
    source: "https://x.com/omni_puzzler",
    kind: "Ops",
  },
  {
    id: "s-20260630-earth",
    title: "EarthBase / EarthMind seeds",
    date: "2026-06-30",
    tags: ["earthbase", "earthmind", "physics", "future"],
    blurb: "Future concept names under One Mission continuity — not Court thrash.",
    source: "https://x.com/omni_puzzler",
    kind: "Idea",
  },
  {
    id: "s-202607-education",
    title: "Debt-free education · one mission school",
    date: "2026-07-05",
    tags: ["education", "debt", "finance", "freedom", "mission"],
    blurb: "Graduate only when out of debt and earning. Strategic investment in human flourishing.",
    source: "https://x.com/omni_puzzler",
    kind: "Thesis",
  },
  {
    id: "s-20260724-gardens",
    title: "I am in full control of me · tend the gardens",
    date: "2026-07-24",
    tags: ["gardens", "sovereignty", "peace", "family"],
    blurb: "Steward sovereignty constraint. Agents never coerce. Five Gardens care is life practice.",
    source: "https://x.com/omni_puzzler",
    kind: "Principle",
  },
];
